# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    assets:
        version: '%env(APP_VERSION)%'
        packages:
            bootstrap:
                base_path: '/bootstrap-5.3.0-dist'
            bootstrap-icon:
                base_path: '/bootstrap-icons-1.10.5'
            jquery:
                base_path: '/jquery-3.7.0'

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
