services:
    php-fpm:
        container_name: task-php-fpm
        build: 
            context: docker
            dockerfile: Dockerfile-php-fpm
        restart: always
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/etc/php-fpm/tzone.ini:/usr/local/etc/php/conf.d/tzone.ini
        ports:
            - 9000:9000
        links:
            - mariadb
        depends_on:
            - mariadb
            - nginx
            - mail
            
    nginx:
        container_name: task-nginx
        image: nginx:latest
        restart: always
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        environment:
            - NGINX_HOST=task.local.paginaemconstrucao.com.br
            - NGINX_PORT=80
            
    mariadb:
        container_name: task-mariadb
        image: mariadb:latest
        restart: always
        working_dir: /app
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=task
            - MARIADB_USER=task
            - MARIADB_PASSWORD=task
            - MARIADB_DATABASE=task
        volumes:
            - type: volume
              source: mariadb
              target: /var/lib/mysql
            - .:/app

    mail:
        container_name: task-mail
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - 8025:8025
            - 1025:1025

volumes:
    mariadb:
