-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 15:16:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `taskdb` ;

-- -----------------------------------------------------
-- Table `taskdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskdb`.`user` (
  `id` BINARY(16) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(180) NOT NULL,
  `roles` LONGTEXT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `name_INDEX` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskdb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskdb`.`task` (
  `id` BINARY(16) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `description` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `owner_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name_INDEX` (`name` ASC),
  INDEX `fk_task_user_idx` (`owner_id` ASC),
  FULLTEXT INDEX `description_FULLTEXT` (`description`),
  FULLTEXT INDEX `name_FULLTEXT` (`name`),
  CONSTRAINT `fk_task_user`
    FOREIGN KEY (`owner_id`)
    REFERENCES `taskdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
